-- Olist_Analytics;

-- =========================================================
-- 09_PRODUCT_CUSTOMER_VALUE_ANALYSIS
-- =========================================================


-- Q1. What is the total revenue generated by each customer?

SELECT TOP 20
    c.customer_unique_id,
    ROUND(SUM(oi.price), 2) AS Total_Revenue
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_unique_id
ORDER BY
    Total_Revenue DESC;


-- Q2. Who are the top 10 highest-value customers?

SELECT TOP 10
    c.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS Total_Orders,
    ROUND(SUM(oi.price), 2) AS Total_Revenue,
    ROUND(
        SUM(oi.price) / COUNT(DISTINCT o.order_id),
        2
    ) AS Average_Order_Value
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_unique_id
ORDER BY
    Total_Revenue DESC;


-- Q3. What is the average customer revenue?

WITH CustomerRevenue AS
(
    SELECT
        c.customer_unique_id,
        SUM(oi.price) AS Customer_Revenue
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_unique_id
)
SELECT
    ROUND(AVG(Customer_Revenue), 2) AS Average_Customer_Revenue
FROM CustomerRevenue;


-- Q4. What is the median customer revenue?

WITH CustomerRevenue AS
(
    SELECT
        c.customer_unique_id,
        SUM(oi.price) AS Customer_Revenue
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_unique_id
),
RankedRevenue AS
(
    SELECT
        Customer_Revenue,
        ROW_NUMBER() OVER (
            ORDER BY Customer_Revenue
        ) AS Row_Num,
        COUNT(*) OVER () AS Total_Rows
    FROM CustomerRevenue
)
SELECT
    ROUND(AVG(Customer_Revenue), 2) AS Median_Customer_Revenue
FROM RankedRevenue
WHERE Row_Num IN
(
    (Total_Rows + 1) / 2,
    (Total_Rows + 2) / 2
);


-- Q5. How many customers generated more than 500 in revenue?

WITH CustomerRevenue AS
(
    SELECT
        c.customer_unique_id,
        SUM(oi.price) AS Customer_Revenue
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_unique_id
)
SELECT
    COUNT(*) AS Customers_Above_500
FROM CustomerRevenue
WHERE Customer_Revenue > 500;


-- Q6. How many customers generated more than 1000 in revenue?

WITH CustomerRevenue AS
(
    SELECT
        c.customer_unique_id,
        SUM(oi.price) AS Customer_Revenue
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_unique_id
)
SELECT
    COUNT(*) AS Customers_Above_1000
FROM CustomerRevenue
WHERE Customer_Revenue > 1000;


-- Q7. What percentage of revenue comes from the top 10% of customers?

WITH CustomerRevenue AS
(
    SELECT
        c.customer_unique_id,
        SUM(oi.price) AS Customer_Revenue
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_unique_id
),
RankedCustomers AS
(
    SELECT
        customer_unique_id,
        Customer_Revenue,
        NTILE(10) OVER (
            ORDER BY Customer_Revenue DESC
        ) AS Revenue_Decile
    FROM CustomerRevenue
)
SELECT
    ROUND(
        SUM(
            CASE
                WHEN Revenue_Decile = 1
                THEN Customer_Revenue
                ELSE 0
            END
        ) * 100.0 / SUM(Customer_Revenue),
        2
    ) AS Top_10_Percent_Revenue_Share
FROM RankedCustomers;


-- Q8. What is the average number of products purchased per customer?

WITH CustomerProducts AS
(
    SELECT
        c.customer_unique_id,
        COUNT(*) AS Product_Items
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_unique_id
)
SELECT
    ROUND(
        AVG(Product_Items),
        2
    ) AS Average_Products_Per_Customer
FROM CustomerProducts;


-- Q9. Which customers purchased the most product items?

SELECT TOP 10
    c.customer_unique_id,
    COUNT(*) AS Product_Items_Purchased
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
INNER JOIN order_items oi
    ON o.order_id = oi.order_id
GROUP BY
    c.customer_unique_id
ORDER BY
    Product_Items_Purchased DESC;


-- Q10. What is the average order value by customer segment?

WITH CustomerOrders AS
(
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS Order_Count,
        SUM(oi.price) AS Total_Revenue
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_unique_id
),
CustomerSegments AS
(
    SELECT
        customer_unique_id,
        Order_Count,
        Total_Revenue,
        CASE
            WHEN Order_Count = 1
                THEN 'One-Time Customer'
            WHEN Order_Count BETWEEN 2 AND 3
                THEN 'Repeat Customer'
            ELSE 'Loyal Customer'
        END AS Customer_Segment
    FROM CustomerOrders
)
SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count,
    ROUND(
        AVG(Total_Revenue),
        2
    ) AS Average_Customer_Revenue,
    ROUND(
        AVG(Total_Revenue / Order_Count),
        2
    ) AS Average_Order_Value
FROM CustomerSegments
GROUP BY
    Customer_Segment
ORDER BY
    Average_Customer_Revenue DESC;


-- Q11. What is the total revenue generated by each customer segment?

WITH CustomerOrders AS
(
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS Order_Count,
        SUM(oi.price) AS Total_Revenue
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_unique_id
),
CustomerSegments AS
(
    SELECT
        customer_unique_id,
        Order_Count,
        Total_Revenue,
        CASE
            WHEN Order_Count = 1
                THEN 'One-Time Customer'
            WHEN Order_Count BETWEEN 2 AND 3
                THEN 'Repeat Customer'
            ELSE 'Loyal Customer'
        END AS Customer_Segment
    FROM CustomerOrders
)
SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count,
    ROUND(
        SUM(Total_Revenue),
        2
    ) AS Total_Revenue
FROM CustomerSegments
GROUP BY
    Customer_Segment
ORDER BY
    Total_Revenue DESC;


-- Q12. What percentage of customers belong to each customer segment?

WITH CustomerOrders AS
(
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS Order_Count
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY
        c.customer_unique_id
),
CustomerSegments AS
(
    SELECT
        customer_unique_id,
        CASE
            WHEN Order_Count = 1
                THEN 'One-Time Customer'
            WHEN Order_Count BETWEEN 2 AND 3
                THEN 'Repeat Customer'
            ELSE 'Loyal Customer'
        END AS Customer_Segment
    FROM CustomerOrders
)
SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count,
    ROUND(
        COUNT(*) * 100.0 /
        SUM(COUNT(*)) OVER (),
        2
    ) AS Customer_Percentage
FROM CustomerSegments
GROUP BY
    Customer_Segment
ORDER BY
    Customer_Percentage DESC;


-- Q13. What is the average number of orders per customer segment?

WITH CustomerOrders AS
(
    SELECT
        c.customer_unique_id,
        COUNT(DISTINCT o.order_id) AS Order_Count
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    GROUP BY
        c.customer_unique_id
),
CustomerSegments AS
(
    SELECT
        customer_unique_id,
        Order_Count,
        CASE
            WHEN Order_Count = 1
                THEN 'One-Time Customer'
            WHEN Order_Count BETWEEN 2 AND 3
                THEN 'Repeat Customer'
            ELSE 'Loyal Customer'
        END AS Customer_Segment
    FROM CustomerOrders
)
SELECT
    Customer_Segment,
    COUNT(*) AS Customer_Count,
    ROUND(
        AVG(Order_Count * 1.0),
        2
    ) AS Average_Orders_Per_Customer
FROM CustomerSegments
GROUP BY
    Customer_Segment
ORDER BY
    Average_Orders_Per_Customer DESC;


-- Q14. Which product categories generate the highest revenue?

SELECT TOP 10
    COALESCE(
        p.product_category_name,
        'Unknown'
    ) AS Product_Category,
    COUNT(DISTINCT oi.order_id) AS Orders,
    SUM(oi.order_item_id * 0 + oi.price) AS Total_Revenue
FROM order_items oi
INNER JOIN products p
    ON oi.product_id = p.product_id
GROUP BY
    COALESCE(
        p.product_category_name,
        'Unknown'
    )
ORDER BY
    Total_Revenue DESC;


-- Q15. What is the average product price by category?

SELECT TOP 10
    COALESCE(
        p.product_category_name,
        'Unknown'
    ) AS Product_Category,
    COUNT(*) AS Product_Items,
    ROUND(
        AVG(oi.price),
        2
    ) AS Average_Product_Price
FROM order_items oi
INNER JOIN products p
    ON oi.product_id = p.product_id
GROUP BY
    COALESCE(
        p.product_category_name,
        'Unknown'
    )
ORDER BY
    Average_Product_Price DESC;


-- Q16. Which product categories have the highest number of repeat purchases?

WITH CustomerCategoryOrders AS
(
    SELECT
        c.customer_unique_id,
        p.product_category_name,
        COUNT(DISTINCT o.order_id) AS Order_Count
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    INNER JOIN products p
        ON oi.product_id = p.product_id
    GROUP BY
        c.customer_unique_id,
        p.product_category_name
)
SELECT TOP 10
    COALESCE(
        product_category_name,
        'Unknown'
    ) AS Product_Category,
    COUNT(*) AS Customer_Category_Combinations,
    SUM(
        CASE
            WHEN Order_Count >= 2
            THEN 1
            ELSE 0
        END
    ) AS Repeat_Purchases
FROM CustomerCategoryOrders
GROUP BY
    COALESCE(
        product_category_name,
        'Unknown'
    )
ORDER BY
    Repeat_Purchases DESC;


-- Q17. What is the average revenue per order?

SELECT
    ROUND(
        SUM(oi.price) /
        COUNT(DISTINCT o.order_id),
        2
    ) AS Average_Revenue_Per_Order
FROM orders o
INNER JOIN order_items oi
    ON o.order_id = oi.order_id;


-- Q18. What is the average number of items per order?

SELECT
    ROUND(
        COUNT(*) * 1.0 /
        COUNT(DISTINCT order_id),
        2
    ) AS Average_Items_Per_Order
FROM order_items;


-- Q19. Which customers have placed the most orders?

SELECT TOP 10
    c.customer_unique_id,
    COUNT(DISTINCT o.order_id) AS Order_Count
FROM orders o
INNER JOIN customers c
    ON o.customer_id = c.customer_id
GROUP BY
    c.customer_unique_id
ORDER BY
    Order_Count DESC;


-- Q20. Which customers have the highest average order value?

WITH CustomerOrderValue AS
(
    SELECT
        c.customer_unique_id,
        o.order_id,
        SUM(oi.price) AS Order_Value
    FROM orders o
    INNER JOIN customers c
        ON o.customer_id = c.customer_id
    INNER JOIN order_items oi
        ON o.order_id = oi.order_id
    GROUP BY
        c.customer_unique_id,
        o.order_id
)
SELECT TOP 10
    customer_unique_id,
    COUNT(*) AS Total_Orders,
    ROUND(
        AVG(Order_Value),
        2
    ) AS Average_Order_Value
FROM CustomerOrderValue
GROUP BY
    customer_unique_id
ORDER BY
    Average_Order_Value DESC;